title: Demo View
image: logo.png
description: Shows how a product catalog page could look with Pages implemented in demo mode.
priority: 4
facts:
  - JS built FSI Pages
  - interactive catalog
  - including hyperlinks to articles
  - demo mode
jsfiddle:
  mapping:
    html: "index.html"
    css: "demo.css"
    js: "demo.js"
  resources:
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/pages/js/fsipages.js"
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/js/bootstrap.bundle.min.js
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@{{dependencies.bootstrapIcons}}/font/bootstrap-icons.css
