overview:
  title: Product Catalog Page
  image: logo.png
  description: Shows how a product catalog page could look.
  order: 1
  facts:
    - JS built FSI Pages
    - interactive catalog
    - including hyperlinks to articles
sample:
  template:
    schema: framework-2023
    components:
      menu:
        logo:
          url: /static/assets/samples/ssi/logo-furniture-gre.svg
          height: 24
        nav:
          - SHOP
          - COLLECTION
          - DECORATION
          - KITCHEN
          - BEDS
          - BATHROOM
      hero: false
      featured: true
      footer: true
      fsi:
        pages: true
      bootstrap:
        icons: false
  mapping:
    html: 'pcp.html'
    js: 'pcp.js'
    css: 'pcp.css'
jsfiddle:
  deploy: true
