overview:
  title: Product Catalog Page
  image: logo.png
  description: Shows how a product catalog page could look.
  order: 1
  facts:
    - JS built FSI Pages
    - interactive catalog
    - including hyperlinks to articles
sample:
  template:
    schema: framework-furniture.html
    components:
      menu: true
      hero: false
      featured: true
      footer: true
      files:
        main: pcp.html
      fsi:
        pages: true
      bootstrap:
        icons: true
  mapping:
    js: 'pcp.js'
    css: 'pcp.css'
jsfiddle:
  deploy: true
