overview:
  title: Product Catalog Page
  image: logo.png
  description: Shows how a product catalog page could look.
  order: 1
  facts:
    - JS built FSI Pages
    - interactive catalog
    - including hyperlinks to articles
sample:
  template:
    schema: framework-furniture
    components:
      menu: true
      hero: false
      featured: true
      footer: true
      fsi:
        pages: true
      bootstrap:
  mapping:
    html: 'pcp.html'
    js: 'pcp.js'
    css: 'pcp.css'
jsfiddle:
  deploy: true
