overview:
  title: Preview and Modal
  image: logo.png
  description: Shows how a simple catalogue overview page with an integrated modal looks.
  order: 3
  facts:
    - JS built FSI Pages
    - modal implementation
    - simple catalogues
schema: bootstrap-taupe
sample:
  menu:
    data: furniture-menu.yml
  highlight: HIGHLIGHT OF THE DAY
  featured:
    data: furniture-featured.yml
  categories: true
  footer: true
  fsi:
    pages: true
  bootstrap:
    icons: true
