title: Product Catalog Page
image: logo.png
description: Shows how a product catalog page could look.
priority: 3
acts:
  - JS built FSI Pages
  - interactive catalog
  - including hyperlinks to articles
jsfiddle:
  mapping:
    html: "index.html"
    css: "pdp.css"
    js: "pdp.js"
  resources:
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/pages/js/fsipages.js"
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/js/bootstrap.bundle.min.js
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@{{dependencies.bootstrapIcons}}/font/bootstrap-icons.css
