title: Travel Guide (Chapters)
image: logo.png
description: Shows how a travel guide with chapters could look.
priority: 6
facts:
  - JS built FSI Pages
  - interactive catalog
  - including chapters
jsfiddle:
  mapping:
    html: "index.html"
    css: "travel.css"
    js: "travel.js"
  resources:
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/pages/js/fsipages.js"
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/js/bootstrap.bundle.min.js
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@{{dependencies.bootstrapIcons}}/font/bootstrap-icons.css
