overview:
  title: Travel Guide (Chapters)
  image: logo.png
  description: Shows how a travel guide with chapters could look.
  order: 2
  facts:
    - JS built FSI Pages
    - interactive catalog
    - including chapters
sample:
  template:
    schema: framework-2023
    components:
      menu:
        logo:
          url: /static/assets/samples/ssi/logo-misc-gre.svg
          height: 24
        nav:
          - ASIA
          - AMERICA
          - AFRICA
          - PACIFIC
          - EUROPE
      footer: true
      fsi:
        pages: true
      bootstrap:
        icons: false
  mapping:
    html: 'travel.html'
    js: 'travel.js'
    css: 'travel.css'
jsfiddle:
  deploy: true
