overview:
  title: Preview and Modal
  image: logo.png
  description: Shows how a simple catalogue overview page with an integrated modal could look.
  order: 3
  facts:
    - JS built FSI Pages
    - modal implementation
    - simple catalogues
sample:
  template:
    schema: framework-furniture
    components:
      menu: true
      featured: true
      categories: true
      footer: true
      fsi:
        pages: true
      bootstrap:
        icons: true
  mapping:
    html: 'modal.html'
    js: 'modal.js'
    css: 'modal.css'
jsfiddle:
  deploy: true
