title: Catalogue Overview (Modal)
image: logo.png
description: Shows how a simple catalogue overview page with an integrated modal could look.
priority: 6
facts:
  - JS built FSI Pages
  - modal implementation
  - simple catalogues
jsfiddle:
  mapping:
    html: "index.html"
    css: "modal.css"
    js: "modal.js"
  resources:
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/touchzoom/js/fsitouchzoom.js"
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/css/bootstrap.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@{{dependencies.bootstrap}}/dist/js/bootstrap.bundle.min.js
    - https://cdn.jsdelivr.net/npm/bootstrap-icons@{{dependencies.bootstrapIcons}}/font/bootstrap-icons.css
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/viewer/js/fsiviewer.js"
