overview:
  title: Preview and Modal
  image: logo.png
  description: Shows how a simple catalogue overview page with an integrated modal could look.
  order: 3
  facts:
    - JS built FSI Pages
    - modal implementation
    - simple catalogues
sample:
  template:
    schema: framework-furniture.html
    components:
      menu: true
      hero: true
      featured: true
      categories: true
      footer: true
      files:
        main: modal.html
      fsi:
        pages: true
        touchZoom: true
      bootstrap:
        icons: true
  mapping:
    js: 'modal.js'
    css: 'modal.css'
jsfiddle:
  deploy: true
